### ISSUE TITLE
Crosschain transaction from ETH to FTM pending for hours

### ISSUE THREAD

**Issue by HodlingHobos** [anyswap/CrossChain-Bridge#17]
The deposit transaction of WETH from the ETH network to the Anyswap FTM bridge was successful:
https://etherscan.io/tx/0x16340e5af7168fd3fa43222f9e58b94b361ee48c9129cc7cd0cc5fa191ae31b8

But the transfer transaction is pending and I don't have any information about it. It takes 1,5 hours already.
Other transactions with WETH from Ethereum to Fantom went through meanwhile and they were initiated later.

Could you support me in that matter

**Comment by jowenshaw** [comment]
sorry for the delay. now its success. https://ftmscan.com/tx/0x7d2d870b5641ad34640590666f6feab8deb6ebfd17349097baa5ae8a36bab6ec

**Comment by HodlingHobos** [comment]
Thank you, received it. What was the problem?
