### ISSUE TITLE
Bridge Transaction not forwarded to OkEx Chain

### ISSUE THREAD

**Issue by dchavezf** [anyswap/CrossChain-Bridge#21]
Hello together,

I did a transactions to swap BUSD from BSC Blockchain to OKeX Blockchain but it seems to be lost / stuck 

The transaction is BSC is ok but i did not receive the money in my metamask wallet for OkEx
https://bscscan.com/tx/0x03907387a573e3f9b1a8373d5e9245d6d3ea1ece3a3df458eb62318af55c9921

Could you help me to rescue that money back?

**Comment by zhaojun-sh** [comment]
This is not bridge transaction.  Please bridge your token on anyswap.exchange
