### ISSUE TITLE
Bridged funds from Polygon to BSC vanished

### ISSUE THREAD

**Issue by Slingshot33** [anyswap/CrossChain-Bridge#24]
Hello there,

I was bridging funds from polygon to BCS and the funds never showed up.

Transaction hash: 
https://polygonscan.com/tx/0x630bd8b2fe6cbc715331ac583476ccd48edb4fbf5d401aeb4b3f9fc467f0d2ac

I would like it to finish the deposit to 0x7357266842453352d654ec551104af3da5c7a1b1

Please help.

Thank you!

**Comment by Slingshot33** [comment]
I am going to try a solution from support.

**Comment by deepanscl** [comment]
Did you succeed?
