### ISSUE TITLE
Been waiting for 4 hours stuck on pending

### ISSUE THREAD

**Issue by hodlthedoor1** [anyswap/CrossChain-Bridge#38]
I've been trying to send USDT from polygon to BSC
The transfer transaction is pending. It takes so many hours.
Need your support please.

https://polygonscan.com/tx/0x6848753561c4e0ff6159ba7cf75f619521f4866b47b9f7389d4db63ff15fc74f

**Comment by zhaojun-sh** [comment]
transaction not on chain.
